USERNAME = 'HaikuThemeBot' #YOUR USERNAME as string
PASSWORD = '051095gs' # YOUR PASSWORD as string

CLIENT_ID = 'B_Xn5mlb34u2Sg'
CLIENT_SECRET = 'KbmXXIGuEbSBErlr_XN2R6GXVa4'

USER_AGENT= ("lumos 0.1")